[project]
name = "books-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pathfinder132", email = "uttejmekala@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "playwright>=1.62.0",
    "requests>=2.34.2",
]

[project.scripts]
books-scraper = "books_scraper:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
